### ISSUE TITLE
[QUESTION] 맞춤형 질문 구조 변경

### ISSUE THREAD

**Issue by yueunfive** [Team-ToYou/ToYou-Server#17]
## 📝 개요
- 기존에 구현된 맞춤형 질문 구조 및 생성 방식을 변경합니다.

## ✅ To-Do
- [ ] 중복 체크 X 👉 관련 DB 구조 변경
- [ ] 맞춤형 질문 생성 로직 변경
- [ ] 질문 데이터 초기화
